# Generated by Django 4.0.2 on 2022-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
